---
title: "Simu Data Example"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Distributions}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

### Add simulation files to BKTR library
```{r}
library(BKTR)
simu_y_path <- system.file('extdata', 'simu_y_full.csv', package = 'BKTR')
simu_y <- BKTR::load_matrix_from_csv(simu_y_path, has_header = FALSE)
usethis::use_data(simu_y, overwrite = TRUE)

simu_omega <- simu_y != 0
usethis::use_data(simu_omega, overwrite = TRUE)

simu_temporal_covs_path <- system.file('extdata', 'simu_temporal_covariates.csv', package = 'BKTR')
simu_temporal_covs <- BKTR::load_matrix_from_csv(simu_temporal_covs_path, has_header = FALSE)
usethis::use_data(simu_temporal_covs, overwrite = TRUE)

simu_spatial_covs_path <- system.file('extdata', 'simu_spatial_covariates.csv', package = 'BKTR')
simu_spatial_covs <- BKTR::load_matrix_from_csv(simu_spatial_covs_path, has_header = FALSE)
usethis::use_data(simu_spatial_covs, overwrite = TRUE)

simu_simulated_covs_path <- system.file('extdata', 'simu_simulated_covariates.csv', package = 'BKTR')
simu_simulated_covs <- BKTR::load_matrix_from_csv(simu_simulated_covs_path, has_header = FALSE)
usethis::use_data(simu_simulated_covs, overwrite = TRUE)

simu_distance_mat_path <- system.file('extdata', 'simu_distance_matrix.csv', package = 'BKTR')
simu_distance_mat <- BKTR::load_matrix_from_csv(simu_distance_mat_path, has_header = FALSE)
usethis::use_data(simu_distance_mat, overwrite = TRUE)
```

### Override BKTRRegressor class init to be able to add a simulated covariate layer and skip periodic_length sampling
```{r}
SimuBKTRRegressor <- R6Class(
    'SimuBKTRRegressor',
    inherit = BKTRRegressor,
    public = list(
        initialize = function(
            bktr_config,
            temporal_covariate_matrix,
            spatial_covariate_matrix,
            spatial_distance_matrix,
            y,
            omega,
            unrelated_covariates
        ) {
            super$initialize(
                bktr_config,
                temporal_covariate_matrix,
                spatial_covariate_matrix,
                spatial_distance_matrix,
                y,
                omega
            )
            unrelated_covariates <- tsr$new_tensor(unrelated_covariates)
            self$covariates <- torch::torch_dstack(c(self$covariates, unrelated_covariates))
            # Add a layer of randomly generated and uncorelated covariates
            self$covariates_dim[['nb_covariates']] <- self$covariates_dim[['nb_covariates']] + 1
        }
    ),

    private = list(
        #~ @description Override sampe_kernel_params to skip periodic_length
        sample_kernel_hparam = function() {
            self$spatial_length_sampler$sample()
            self$decay_scale_sampler$sample()
        }
    )
)
```

### Create function that allows to run BKTR on simulated data
```{r}
run_simu_bktr <- function(
    results_export_dir,
    nb_runs = 1,
    burn_in_iter = 2,
    max_iter = 4,
    torch_seed = 10,
    torch_device = 'cpu'
) {
    for (i in 1:nb_runs) {
        ex_bktr_config <- BKTRConfig$new(
            rank_decomp = 10,
            max_iter = max_iter,
            burn_in_iter = burn_in_iter,
            temporal_kernel_fn_name = 'se',
            has_stabilizing_diag = TRUE,
            kernel_time_segment_duration = 1 / 10,
            results_export_dir = './output',
            sampled_beta_indexes = c(860, 1949, 5519, 6338, 9207, 10435, 15034, 15868, 16059, 16944) + 1,
            sampled_y_indexes = c(52, 4046, 12979, 13129, 15673, 17807) + 1,
            torch_seed = torch_seed * i,
            torch_device = torch_device
        )

        ex_bktr_regressor <- SimuBKTRRegressor$new(
            bktr_config = ex_bktr_config,
            temporal_covariate_mat = simu_temporal_covs,
            spatial_covariate_mat = simu_spatial_covs,
            spatial_distance_mat = simu_distance_mat,
            y = simu_y,
            omega = simu_omega,
            unrelated_covariates = simu_simulated_covs
        )
        ex_bktr_regressor$mcmc_sampling()
    }
}
```

### Run BKTR
```{r}
run_simu_bktr(
    nb_runs = 1,
    results_export_dir = './output',
    burn_in_iter = 2,
    max_iter = 4,
    torch_seed = 900,
    torch_device = 'cpu'
)
```
